version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/var/www
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - backend

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: craftscene_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_UPLOAD_LIMIT: 1000000000
      UPLOAD_LIMIT: 100000000
    ports:
      - "8080:80"

volumes:
  mysql-data:
