apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ingress-nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 702551696126.dkr.ecr.eu-central-1.amazonaws.com/craftscene-php:latest
        ports:
        - containerPort: 9000  
        env:
          - name: DB_CONNECTION
            value: "mysql"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: rds-endpoint
                key: endpoint
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: rds-username
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-password
                key: password
          - name: DB_DATABASE
            value: craftscene_db
          - name: DB_PORT
            value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx 
  name: php-app-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000


