apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: craftscene-app
data:
  nginx.conf: |
    events {
      worker_connections  1024;  ## Default: 1024
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen       80;
        server_name  localhost;

        # Document root and index files
        root   /var/www/public;
        index  index.php index.html;

        # Error and access log files
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        # PHP script handling
        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Static file handling
        location / {
          try_files $uri $uri/ /index.php?$query_string;
          gzip_static on;
        }
      }
    }
