apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftscene-deployment
  namespace: craftscene-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craftscene
  template:
    metadata:
      labels:
        app: craftscene
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: 361749389927.dkr.ecr.me-south-1.amazonaws.com/craftscene-nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: php-fpm
          env:
            - name: DB_HOST
              value: rds-cluster.cluster-cleu4grfvxuc.me-south-1.rds.amazonaws.com
            - name: DB_USERNAME
              value: craftscene
            - name: DB_PASSWORD
              value: 61l=%z1MI?*M5]my
            - name: DB_DATABASE
              value: craftscene
          image: 361749389927.dkr.ecr.me-south-1.amazonaws.com/craftscene-php
          ports:
            - containerPort: 9000
#        - name: phpmyadmin
#          image: phpmyadmin/phpmyadmin:latest
#          env:
#            - name: PMA_HOST
#              value: mysql-service
#          ports:
#            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: craftscene-app-service
  namespace: craftscene-app
spec:
  selector:
    app: craftscene
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: phpmyadmin-service
#spec:
#  type: NodePort
#  selector:
#    app: craftscene
#  ports:
#    - port: 8080
#      targetPort: 80
