apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftscene-php-deployment
  namespace: craftscene-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craftscene-php
  template:
    metadata:
      labels:
        app: craftscene-php
    spec:
      containers:
        - name: php-fpm
          image: 361749389927.dkr.ecr.me-south-1.amazonaws.com/craftscene-php:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-endpoint
                  key: endpoint
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-password
                  key: password
            - name: DB_DATABASE
              value: craftscene

---
apiVersion: v1
kind: Service
metadata:
  name: craftscene-php-service
  namespace: craftscene-app
spec:
  selector:
    app: craftscene
  ports:
    - port: 9000
      targetPort: 9000
  type: NodePort
